# Lab 21 - Broadcasting in Numpy

In [1]:
# 1. For a given problem you have numpy array of observation which is 1x3 vector and codes
# which 3x3 matrix. Calculate difference between code and observation, take its sqaure and
# calculate its sum across axis 1 and take square root of those results. 

#numpy array of observation
import numpy as np

#In a two-dimensional vector, the elements of axis 0 are rows and the elements of axis 1 are columns.

observation = np.array([10, 5, 9])
code = np.array([[24, 32, 25],
                 [26, 27, 15],
                 [13, 40, 37]])


In [3]:
print("Observation Matrix:\n", observation)

print("\n Code Matrix:\n", code)


Observation Matrix:
 [10  5  9]

 Code Matrix:
 [[24 32 25]
 [26 27 15]
 [13 40 37]]


In [7]:
difference = code - observation
print("\nDifference between code and observation:\n", difference)


Difference between code and observation:
 [[14 27 16]
 [16 22  6]
 [ 3 35 28]]


In [13]:
squared_diff = difference ** 2
print("\nSquare of the Difference:\n", squared_diff)


Square of the Difference:
 [[ 196  729  256]
 [ 256  484   36]
 [   9 1225  784]]


In [14]:
sum_squared_diff = np.sum(squared_diff, axis=1)
print("\nSum of squared differences across axis 1:\n", sum_squared_diff)


Sum of squared differences across axis 1:
 [1181  776 2018]


In [15]:
output = np.sqrt(sum_squared_diff)

print("\nSquare Root of the Sum of Squared difference:\n", output)


Square Root of the Sum of Squared difference:
 [34.36568055 27.85677655 44.92215489]
